### ISSUE TITLE
It dont work

### ISSUE THREAD

**Issue by LPDMinecraft** [Tfarcenim/XLPackets#1]
I have a server with the Create mod and there I reported the bug. They said these mod can fix it. But I think I made something wrong. I uploaded Bootstrap and XL Packets on my server and on my client and the same message came and I dont come on the server. Can you please help me.

**Comment by Tfarcenim** [comment]
not enough context

**Comment by LPDMinecraft** [comment]
![grafik](https://user-images.githubusercontent.com/65708374/111783643-b3fe1580-88ba-11eb-8d3a-4edfc5ec76b0.png)

**Comment by Tfarcenim** [comment]
alright, I need logs from the client

**Comment by LPDMinecraft** [comment]
?

**Comment by Tfarcenim** [comment]
gonna close as resolved due to lack of followup
