### ISSUE TITLE
XL packets causing other mods to not load correctly 1.19.2

### ISSUE THREAD

**Issue by Hammerkirby123** [Tfarcenim/XLPackets#10]
The error I'm getting on the following mods is this
java.lang.reflect.invocationtargetexception null
Naturalist, Paragon, Deeper and Darker, GeckoLib, The graveyard, Ars Nouveau, and even forge itself is having trouble with this mod
[crash-2023-04-23_22.55.41-fml.txt](https://github.com/Tfarcenim/XLPackets/files/11305966/crash-2023-04-23_22.55.41-fml.txt)
^crash report
[latest.log](https://github.com/Tfarcenim/XLPackets/files/11305967/latest.log)
^latest log

**Comment by Tfarcenim** [comment]
Immersive portals issue
