### ISSUE TITLE
1.20.1 Forge Update?

### ISSUE THREAD

**Issue by KiwiParis** [Tfarcenim/XLPackets#11]
Not really an issue or anything, but I was just wondering if there would be an update for Forge XLpackets for 1.20.1 as Origins ++ has updated and I've been wanting to play with it!

Thank you for your time :)

**Comment by gabriel-fresan** [comment]
Call me crazy, but i just manually installed the latest version, `xlpackets-1.18.2-2.1.jar` and it worked fine with `Origins++`

**Comment by Maybeian** [comment]
> Call me crazy, but i just manually installed the latest version, `xlpackets-1.18.2-2.1.jar` and it worked fine with `Origins++`

Thank you so much this is the only thing that worked after hours of troubleshooting and trying substitute mods

**Comment by Tfarcenim** [comment]
done
