### ISSUE TITLE
Any Chance for a 1.17 update? 

### ISSUE THREAD

**Issue by Merith-TK** [Tfarcenim/XLPackets#3]
Read title?

**Comment by Tfarcenim** [comment]
No mixins, no port (on Forge)

**Comment by Merith-TK** [comment]
Was talking about for fabric

**Comment by Merith-TK** [comment]
Wait a bloody second, 

I just found [xl-packets-fabric](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric). so I've been using the wrong mod.. this entire time?!
