### ISSUE TITLE
Incompatibility with magma (1.16.5)

### ISSUE THREAD

**Issue by Linksapprentice** [Tfarcenim/XLPackets#9]
I was running a heavily modded 16.5 server that relied on your mod, because it contains many large mods. Because of performance issues on a cheap server (and using almost all compatible performance mods) I decided to see of plugins via magma could help with performance issues. The pluggins seemingly helped because the resource usage is a lot better, but now I'm getting the packet is too large error whenever I try to join the server. I have it installed on server and client and the only thing I changed was adding magma. 

the exact issue is "Internal Exception: io.netty.handler.codec.DecoderException: Badly Compressed Packet - size of 8826727 is larger than maximum of 2097152

**Comment by Tfarcenim** [comment]
Hybrid servers are buggyand unsupported
